"""Add join_date back to NGOMember

Revision ID: 8864276227ad
Revises: 
Create Date: 2025-04-10 18:04:26.175630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8864276227ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngo_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_ngo_member_email'), ['email'], unique=False)
        batch_op.drop_column('role')
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ngo_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_index(batch_op.f('ix_ngo_member_email'))
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('designation')

    # ### end Alembic commands ###
